# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Make Forecasts

on:
  workflow_dispatch:
#   schedule:
    # * is a special character in YAML so you have to quote this string
#     - cron: "10 * * * *"
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Montreal
      - name: Forecast Inflow
        if: always()
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/forecast_inflow.py
      - name: Forecast Inflow With Weather
        if: always()
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/forecast_inflow_with_weather.py
      - name: Forecast Prepod
        if: always()
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/forecast_prepod.py
      - name: Forecast VerticalTBS
        if: always()
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/forecast_verticalTBS.py
      - name: Stretcher Occupancy
        if: always()
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/forecast_stretcher_occupancy.py
      - name: Forecast Daily Visits
        if: always()
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
        run: |
          python scripts/forecast_daily_visits.py
      - name: Forecast Daily Visits With Weather
        if: always()
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/forecast_daily_visits_with_weather.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: always()
        with:
          push_options: '--force'
