# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Make Forecasts

on:
  workflow_dispatch:
#   schedule:
    # * is a special character in YAML so you have to quote this string
#     - cron: "10 * * * *"
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Montreal
      - name: Forecast Inflow
        run: |
          python scripts/forecast_inflow.py
      - name: Forecast Prepod
        run: |
          python scripts/forecast_prepod.py
      - name: Forecast VerticalTBS
        run: |
          python scripts/forecast_verticalTBS.py
      - name: Forecast Stretcher Occupancy
        run: |
          python scripts/forecast_stretcher_occupancy.py
      - name: Forecast Daily Visits
        run: |
          python scripts/forecast_daily_visits.py
#       - name: Forecast Daily Visits With Weather
#         run: |
#           python scripts/forecast_daily_visits_with_weather.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
