# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Stretcher Occupancy

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "10 * * * *"
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
#           cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Montreal
      - name: Stretcher Occupancy
        if: always()
        run: |
          python scripts/stretcher_occupancy.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: always()
        with:
          push_options: '--force'