# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Train Forecast Models

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 1 * * *"
  push:
    branches: [main]
# on:
#   workflow_run:
#     workflows: ["Update data with current hourly report"]
#     types:
#       - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install install -r requirements.txt
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Montreal
      - name: Create Inflow Model
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/create_inflow_model.py
      - name: Create Inflow Model with Weather
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/create_inflow_model_with_weather.py
      - name: Create Prepod Model
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/create_prepod_model.py
      - name: Create VerticalTBS Model
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/create_verticalTBS_model.py
      - name: Create Stretcher Occupancy Model
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/create_stretcher_occupancy_model.py
      - name: Create Daily Visits Model
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/create_daily_visits_model.py
      - name: Create Daily Visits Model With Weather
        env:
          COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        run: |
          python scripts/create_daily_visits_model_with_weather.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
